all:
  vars:
    # The generated inventory is assumed to be used from the clab host.
    # Hence no http proxy should be used. Therefore we make sure the http
    # module does not attempt using any global http proxy.
    ansible_httpapi_use_proxy: false
  children:
    nokia_srlinux:
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: sros
        ansible_user: admin
        ansible_password: NokiaSrl1!
        ansible_network_cli_ssh_type: libssh
      hosts:
        srl1:
          ansible_host: 172.20.20.2
        srl2:
          ansible_host: 172.20.20.3
